import Head from 'next/head';
import Layout from '../components/layout';
import HomePage from '../pagesContent/homePage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mdcraftbeerfestival</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomePage />
      </Layout>
    </div>
  );
}
